// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// update_edge_counts
void update_edge_counts(IntegerVector ids, CharacterVector votes, IntegerMatrix adj_mat_agree, IntegerMatrix adj_mat_total);
RcppExport SEXP _riigikogu_update_edge_counts(SEXP idsSEXP, SEXP votesSEXP, SEXP adj_mat_agreeSEXP, SEXP adj_mat_totalSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type votes(votesSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type adj_mat_agree(adj_mat_agreeSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type adj_mat_total(adj_mat_totalSEXP);
    update_edge_counts(ids, votes, adj_mat_agree, adj_mat_total);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_riigikogu_update_edge_counts", (DL_FUNC) &_riigikogu_update_edge_counts, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_riigikogu(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
