# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_edge_counts <- function(ids, votes, adj_mat_agree, adj_mat_total) {
    invisible(.Call('_riigikogu_update_edge_counts', PACKAGE = 'riigikogu', ids, votes, adj_mat_agree, adj_mat_total))
}

